users = {
    "Margarette": "online",
    "Marisol": "offline",
    "Mozelle": "online",
    "Jessy": "offline",
    "Leon": "offline",
    "Bette": "online",
    "Emilie": "offline",
    "Ernesto": "offline",
    "Oran": "online",
    "Octavia":"offline", 
    "Joelle": "online",
    "Virginie":"offline",
    "Kelton":"online",
    "Velda":"online",
    "Andreanne":"offline",
    "Litzy":"offline",
    "Callie":"online",
    "Dell":"online",
    "Hillary":"online",
    "Royal":"online",
    "Jevon":"online",
    "Kaylee":"online",
    "Keyon":"online",
    "Oran":"online",
    "Guadalupe":"offline",
    "Brian":"offline",
    "Kiarra":"online",
    "Orlando":"offline",
    "Buck":"online",
    "Earlene":"offline",
    "Kaycee":"online",
    "Kiley":"online",
    "Ashleigh":"offline",
    "Kaleb":"offline",
    "Adrianna":"offline",
    "Eliseo":"online",
    "Mae":"offline",
    "Antonina":"offline",
    "Oscar":"offline",
    "Clovis":"online",
    "Elizabeth":"offline",
    "Janiya":"online",
    "Katelin":"online",
    "Gavin":"offline",
    "Vita":"online",
    "Joyce":"offline",
    "Karson":"offline",
    "Orion":"online",
    "Erwin":"online",
    "Tyra":"offline",
    "Candace":"online",
    "Wayne":"online",
    "Ashley":"online",
    "Carolyn":"offline",
    "Fae":"online",
    "Gerald":"offline",
    "Lucious":"online",
    "Sasha":"offline",
    "Burnice":"online",
    "Kameron":"online",
    "Keshaun":"online",
    "Annetta":"offline",
    "Demarco":"online",
    "Lottie":"online",
    "Libbie":"online",
    "Eliane":"online",
    "Julio":"online",
    "Griffin":"offline",
    "Bernadette":"offline",
    "Zella":"offline",
    "Wilburn":"offline",
    "Jamel":"offline",
    "Claud":"online",
    "Karlee":"offline",
    "Alysson":"offline",
    "Ebony":"offline",
    "Rebeca":"online"
}

